
import React, { useMemo, useState, useRef } from 'react';
import { PlanOutput, Translation, PlanCompletion } from '../types';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface PlanDisplayProps {
  plan: PlanOutput;
  completion: PlanCompletion;
  onToggle: (category: keyof PlanCompletion, index: number) => void;
  onReorder: (category: 'morning' | 'afternoon' | 'evening' | 'habits', index: number, direction: 'up' | 'down') => void;
  onSort: (category: 'morning' | 'afternoon' | 'evening' | 'habits') => void;
  t: Translation;
}

const PlanDisplay: React.FC<PlanDisplayProps> = ({ plan, completion, onToggle, onReorder, onSort, t }) => {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState<string | null>(null);
  const planRef = useRef<HTMLDivElement>(null);

  const progress = useMemo(() => {
    const total = completion.morning.length + completion.afternoon.length + completion.evening.length + completion.habits.length;
    const completed = [...completion.morning, ...completion.afternoon, ...completion.evening, ...completion.habits].filter(Boolean).length;
    return total > 0 ? Math.round((completed / total) * 100) : 0;
  }, [completion]);

  const generatePlanText = () => {
    return `
# ${plan.title}
${plan.summary}

## Daily Routine
### Morning
${plan.dailyRoutine.morning.map(i => `- [ ] ${i}`).join('\n')}

### Afternoon
${plan.dailyRoutine.afternoon.map(i => `- [ ] ${i}`).join('\n')}

### Evening
${plan.dailyRoutine.evening.map(i => `- [ ] ${i}`).join('\n')}

## Habits to Build
${plan.habits.map(h => `- ${h}`).join('\n')}

## Milestones
${plan.milestones.map(m => `- ${m}`).join('\n')}

> ${plan.quote}
Generated by Groovie AI Planner
    `.trim();
  };

  const handleExportPNG = async () => {
    if (!planRef.current) return;
    setExporting('png');
    try {
      const canvas = await html2canvas(planRef.current, {
        backgroundColor: '#0d1b2a',
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const dataUrl = canvas.toDataURL('image/png');
      const link = document.createElement('a');
      link.download = `Groovie_Plan_${plan.title.replace(/\s+/g, '_')}.png`;
      link.href = dataUrl;
      link.click();
    } catch (error) {
      console.error('PNG export failed', error);
    } finally {
      setExporting(null);
    }
  };

  const handleExportPDF = async () => {
    if (!planRef.current) return;
    setExporting('pdf');
    try {
      const canvas = await html2canvas(planRef.current, {
        backgroundColor: '#0d1b2a',
        scale: 2,
        useCORS: true,
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width / 2, canvas.height / 2],
      });
      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2);
      pdf.save(`Groovie_Plan_${plan.title.replace(/\s+/g, '_')}.pdf`);
    } catch (error) {
      console.error('PDF export failed', error);
    } finally {
      setExporting(null);
    }
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([generatePlanText()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Groovie_Plan_${plan.title.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatePlanText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    const shareData = {
      title: plan.title,
      text: `Check out my Groovie AI Growth Plan: ${plan.summary}`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        console.error("Error sharing", err);
      }
    } else {
      handleCopy();
    }
  };

  const CheckItem: React.FC<{ 
    label: string, 
    checked: boolean, 
    idx: number,
    category: 'morning' | 'afternoon' | 'evening' | 'habits',
    onToggle: () => void,
    colorClass: string 
  }> = ({ label, checked, idx, category, onToggle, colorClass }) => (
    <li 
      className={`group flex items-start space-x-3 p-3 rounded-xl transition-all duration-300 ${
        checked ? 'bg-white/5 opacity-50 line-through text-slate-500' : 'hover:bg-white/5 text-slate-200'
      }`}
    >
      <div 
        onClick={onToggle}
        className={`mt-0.5 flex-shrink-0 w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all cursor-pointer ${
          checked ? `bg-${colorClass} border-${colorClass}` : `border-slate-700 group-hover:border-${colorClass}`
        }`}
      >
        {checked && (
          <svg className="w-4 h-4 text-slate-900" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={4}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
        )}
      </div>
      <span onClick={onToggle} className="text-lg leading-snug flex-1 cursor-pointer">{label}</span>
      
      {!exporting && (
        <div className="flex flex-col space-y-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button 
            onClick={(e) => { e.stopPropagation(); onReorder(category, idx, 'up'); }}
            className="p-0.5 hover:text-[#f2a65a] text-slate-600 transition-colors"
            title="Move Up"
          >
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clipRule="evenodd" /></svg>
          </button>
          <button 
            onClick={(e) => { e.stopPropagation(); onReorder(category, idx, 'down'); }}
            className="p-0.5 hover:text-[#f2a65a] text-slate-600 transition-colors"
            title="Move Down"
          >
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" /></svg>
          </button>
        </div>
      )}
    </li>
  );

  const SectionHeader: React.FC<{ 
    icon: string, 
    title: string, 
    colorClass: string,
    category: 'morning' | 'afternoon' | 'evening' | 'habits' 
  }> = ({ icon, title, colorClass, category }) => (
    <div className="flex items-center justify-between mb-8">
      <div className="flex items-center space-x-3">
        <span className="text-4xl">{icon}</span>
        <h3 className={`text-3xl font-bold text-${colorClass}`}>{title}</h3>
      </div>
      {!exporting && (
        <button 
          onClick={() => onSort(category)}
          className="text-[10px] font-bold uppercase tracking-widest px-3 py-1 bg-slate-800 text-slate-400 rounded-full hover:bg-slate-700 hover:text-white transition-all flex items-center space-x-1"
        >
          <span>A-Z</span>
          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 4h13M3 8h9m-9 4h6m4 0l4-4m0 0l4 4m-4-4v12" /></svg>
        </button>
      )}
    </div>
  );

  return (
    <div className="max-w-6xl mx-auto mb-24 px-4 animate-in fade-in slide-in-from-bottom-12 duration-1000">
      <div className="mb-12 glass-card rounded-[2rem] p-6 md:p-8 flex flex-col md:flex-row items-center justify-between border-b-4 border-b-[#ee6c4d]">
        <div className="mb-4 md:mb-0">
          <h2 className="font-groovy text-3xl text-[#f2a65a] mb-1">{t.progressTitle}</h2>
          <p className="text-slate-400 font-medium">{progress}% Complete</p>
        </div>
        <div className="w-full md:w-2/3 h-6 bg-slate-800 rounded-full overflow-hidden shadow-inner p-1">
          <div 
            className="h-full bg-gradient-to-r from-[#ee6c4d] to-[#f2a65a] rounded-full transition-all duration-700 ease-out shadow-[0_0_15px_rgba(238,108,77,0.4)]"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      <div ref={planRef} className="glass-card rounded-[3rem] p-8 md:p-16 border-l-[12px] border-l-[#f2a65a] shadow-[0_0_100px_rgba(0,0,0,0.5)] relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-full opacity-[0.02] pointer-events-none retro-stripes"></div>

        <div className="mb-16 text-center relative z-10">
          <h2 className="font-groovy text-5xl md:text-7xl text-[#f2a65a] mb-6 drop-shadow-xl">{plan.title}</h2>
          <div className="max-w-3xl mx-auto bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm">
            <p className="text-2xl text-slate-300 italic font-light leading-relaxed">"{plan.summary}"</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-16 relative z-10">
          <div className="space-y-4">
            <SectionHeader icon="🌅" title={t.morning} colorClass="[#ee6c4d]" category="morning" />
            <ul className="space-y-1">
              {plan.dailyRoutine.morning.map((item, idx) => (
                <CheckItem 
                  key={`${idx}-${item}`}
                  label={item} 
                  checked={completion.morning[idx]} 
                  idx={idx}
                  category="morning"
                  onToggle={() => onToggle('morning', idx)}
                  colorClass="[#ee6c4d]"
                />
              ))}
            </ul>
          </div>

          <div className="space-y-4">
            <SectionHeader icon="☀️" title={t.afternoon} colorClass="[#f2a65a]" category="afternoon" />
            <ul className="space-y-1">
              {plan.dailyRoutine.afternoon.map((item, idx) => (
                <CheckItem 
                  key={`${idx}-${item}`}
                  label={item} 
                  checked={completion.afternoon[idx]} 
                  idx={idx}
                  category="afternoon"
                  onToggle={() => onToggle('afternoon', idx)}
                  colorClass="[#f2a65a]"
                />
              ))}
            </ul>
          </div>

          <div className="space-y-4">
            <SectionHeader icon="🌙" title={t.evening} colorClass="slate-400" category="evening" />
            <ul className="space-y-1">
              {plan.dailyRoutine.evening.map((item, idx) => (
                <CheckItem 
                  key={`${idx}-${item}`}
                  label={item} 
                  checked={completion.evening[idx]} 
                  idx={idx}
                  category="evening"
                  onToggle={() => onToggle('evening', idx)}
                  colorClass="slate-500"
                />
              ))}
            </ul>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 relative z-10">
          <div className="glass-card p-10 rounded-[2rem] bg-white/5 border border-white/10 transform transition-transform hover:scale-[1.01]">
            <SectionHeader icon="✨" title={t.habitsTitle} colorClass="[#f2a65a]" category="habits" />
            <div className="grid grid-cols-1 gap-4">
              {plan.habits.map((habit, idx) => (
                <div 
                  key={`${idx}-${habit}`}
                  className={`group p-5 rounded-2xl border transition-all flex items-center space-x-4 ${
                    completion.habits[idx] 
                    ? 'bg-[#f2a65a]/10 border-[#f2a65a]/30 opacity-60 grayscale' 
                    : 'bg-white/5 border-white/5 hover:border-[#f2a65a]/50'
                  }`}
                >
                  <div onClick={() => onToggle('habits', idx)} className="flex-shrink-0 cursor-pointer">
                    <span className={`font-groovy text-xl ${completion.habits[idx] ? 'text-slate-500' : 'text-[#ee6c4d]'}`}>{idx + 1}</span>
                  </div>
                  <span onClick={() => onToggle('habits', idx)} className={`text-lg flex-1 cursor-pointer ${completion.habits[idx] ? 'line-through text-slate-500' : 'text-slate-200'}`}>{habit}</span>
                  {!exporting && (
                    <div className="flex flex-col space-y-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button onClick={() => onReorder('habits', idx, 'up')} className="p-1 hover:text-[#ee6c4d] text-slate-600 transition-colors"><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" /></svg></button>
                      <button onClick={() => onReorder('habits', idx, 'down')} className="p-1 hover:text-[#ee6c4d] text-slate-600 transition-colors"><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" /></svg></button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="glass-card p-10 rounded-[2rem] bg-white/5 border border-white/10 transform transition-transform hover:scale-[1.01]">
            <h3 className="font-groovy text-3xl text-[#ee6c4d] mb-8 flex items-center space-x-4">
               <span className="bg-[#ee6c4d]/20 p-3 rounded-2xl">🚀</span>
               <span>{t.milestonesTitle}</span>
            </h3>
            <div className="space-y-8 relative">
              <div className="absolute left-[23px] top-4 bottom-4 w-1 bg-gradient-to-b from-[#ee6c4d] to-transparent rounded-full opacity-30" />
              {plan.milestones.map((ms, idx) => (
                <div key={idx} className="relative pl-14 group">
                  <div className="absolute left-0 top-1 w-12 h-12 rounded-2xl bg-slate-800 border-2 border-[#ee6c4d]/30 flex items-center justify-center transition-all group-hover:scale-110 group-hover:bg-[#ee6c4d]/10">
                    <div className="w-3 h-3 rounded-full bg-[#f2a65a] animate-pulse" />
                  </div>
                  <p className="text-xl text-slate-200 leading-relaxed font-medium">{ms}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-20 text-center p-12 bg-gradient-to-br from-[#ee6c4d]/20 to-transparent rounded-[3rem] border border-[#ee6c4d]/30 relative z-10">
          <svg className="w-16 h-16 text-[#ee6c4d]/20 absolute top-4 left-4" fill="currentColor" viewBox="0 0 24 24">
            <path d="M14.017 21L14.017 18C14.017 16.8954 13.1216 16 12.017 16C10.9124 16 10.017 16.8954 10.017 18L10.017 21H4.017V11C4.017 6.02944 8.04645 2 13.017 2H14.017C18.9876 2 23.017 6.02944 23.017 11V21H14.017Z" />
          </svg>
          <p className="text-3xl md:text-4xl font-groovy text-white italic drop-shadow-lg leading-snug">
            "{plan.quote}"
          </p>
        </div>
      </div>

      {/* Export Section Outside capturing div to keep buttons off the export */}
      <div className="mt-12 text-center">
        <h3 className="font-groovy text-3xl text-slate-400 mb-8 uppercase tracking-widest">{t.shareTitle}</h3>
        <div className="flex flex-wrap items-center justify-center gap-4">
          <button 
            disabled={!!exporting}
            onClick={handleExportPDF}
            className="px-6 py-4 bg-[#415a77] text-white font-bold rounded-2xl flex items-center space-x-3 hover:scale-105 active:scale-95 transition-all shadow-lg disabled:opacity-50"
          >
            {exporting === 'pdf' ? (
              <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            ) : (
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>
            )}
            <span>{t.downloadPDF}</span>
          </button>

          <button 
            disabled={!!exporting}
            onClick={handleExportPNG}
            className="px-6 py-4 bg-gradient-to-r from-[#7209b7] to-[#f72585] text-white font-bold rounded-2xl flex items-center space-x-3 hover:scale-105 active:scale-95 transition-all shadow-lg disabled:opacity-50"
          >
            {exporting === 'png' ? (
              <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            ) : (
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
            )}
            <span>{t.downloadPNG}</span>
          </button>

          <button 
            onClick={handleShare}
            className="px-6 py-4 bg-gradient-to-r from-[#ee6c4d] to-[#f2a65a] text-white font-bold rounded-2xl flex items-center space-x-3 hover:scale-105 active:scale-95 transition-all shadow-lg"
          >
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" /></svg>
            <span>{t.shareButton}</span>
          </button>

          <button 
            onClick={handleDownloadMarkdown}
            className="px-6 py-4 bg-slate-800 border border-white/10 text-white font-bold rounded-2xl flex items-center space-x-3 hover:bg-slate-700 hover:scale-105 active:scale-95 transition-all"
          >
            <svg className="w-6 h-6 text-[#f2a65a]" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
            <span>{t.downloadButton}</span>
          </button>

          <button 
            onClick={handleCopy}
            className={`px-6 py-4 bg-white/5 border border-white/10 text-white font-bold rounded-2xl flex items-center space-x-3 hover:bg-white/10 hover:scale-105 active:scale-95 transition-all ${copied ? 'ring-2 ring-green-500/50' : ''}`}
          >
            {copied ? (
              <svg className="w-6 h-6 text-green-500 animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
            ) : (
              <svg className="w-6 h-6 text-[#ee6c4d]" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
            )}
            <span>{copied ? t.copySuccess : t.copyButton}</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default PlanDisplay;
